/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CitizenRole;

import Business.Address.Address;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.CitizenEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.City.CitizenOrganization;
import Business.Organization.Organization;
import Business.Person.CitizenOrganizationEmployee;
import Business.Role.CitizenRole;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author deepa
 */
public class CitizenRegistration extends javax.swing.JPanel {

    private  JPanel userProcessContainer;
    private  Organization org;
    private  EcoSystem system;
    private  String OTP_GEN="";
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public CitizenRegistration(JPanel userProcessContainer, Organization org, EcoSystem system) {
        initComponents();
     this.userProcessContainer = userProcessContainer;
     this.org = org;
     this.system = system;
     populateNetworkComboBox();
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordJTxt = new javax.swing.JTextField();
        firstNameJTxt1 = new javax.swing.JTextField();
        maleJRadiobtn = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        pincodeJTxt = new javax.swing.JTextField();
        lastNameJTxt1 = new javax.swing.JTextField();
        ageJTxt1 = new javax.swing.JTextField();
        userNameJTxt = new javax.swing.JTextField();
        sumbitJBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phoneNoJTxt2 = new javax.swing.JTextField();
        emailIdJTxt1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        addtxt1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addTxt2 = new javax.swing.JTextField();
        aptNumberTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(110, 89, 222));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Email Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Address Line 1");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Pincode");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Phone Number");

        passwordJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordJTxt.setBorder(new javax.swing.border.MatteBorder(null));

        firstNameJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameJTxt1.setBorder(new javax.swing.border.MatteBorder(null));
        firstNameJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameJTxt1KeyTyped(evt);
            }
        });

        maleJRadiobtn.setBackground(new java.awt.Color(153, 153, 153));
        maleJRadiobtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maleJRadiobtn.setText("Male");
        maleJRadiobtn.setAutoscrolls(true);
        maleJRadiobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        maleJRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJRadiobtnActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setAutoscrolls(true);
        jRadioButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        pincodeJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pincodeJTxt.setBorder(new javax.swing.border.MatteBorder(null));
        pincodeJTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pincodeJTxtKeyTyped(evt);
            }
        });

        lastNameJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameJTxt1.setBorder(new javax.swing.border.MatteBorder(null));
        lastNameJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameJTxt1KeyTyped(evt);
            }
        });

        ageJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ageJTxt1.setBorder(new javax.swing.border.MatteBorder(null));
        ageJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageJTxt1KeyTyped(evt);
            }
        });

        userNameJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameJTxt.setBorder(new javax.swing.border.MatteBorder(null));

        sumbitJBtn.setBackground(new java.awt.Color(153, 153, 153));
        sumbitJBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sumbitJBtn.setText("Register");
        sumbitJBtn.setFocusTraversalPolicyProvider(true);
        sumbitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitJBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("User Name");

        phoneNoJTxt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNoJTxt2.setBorder(new javax.swing.border.MatteBorder(null));
        phoneNoJTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoJTxt2KeyTyped(evt);
            }
        });

        emailIdJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailIdJTxt1.setBorder(new javax.swing.border.MatteBorder(null));

        backJButton.setBackground(new java.awt.Color(51, 51, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("New Citizen Register Here");

        addtxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addtxt1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Address Line 2");

        addTxt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addTxt2.setBorder(new javax.swing.border.MatteBorder(null));

        aptNumberTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aptNumberTxt.setBorder(new javax.swing.border.MatteBorder(null));
        aptNumberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aptNumberTxtKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Apt Number");

        networkJComboBox.setBackground(new java.awt.Color(153, 153, 153));
        networkJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(50, 50, 50)
                        .addComponent(phoneNoJTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(lastNameJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(maleJRadiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sumbitJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aptNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(emailIdJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel16)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pincodeJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(firstNameJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(userNameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(ageJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(sumbitJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleJRadiobtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincodeJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoJTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isLetter(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE || character == KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_firstNameJTxt1KeyTyped

    private void maleJRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleJRadiobtnActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void pincodeJTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pincodeJTxtKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pincodeJTxtKeyTyped

    private void lastNameJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isLetter(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE || character == KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lastNameJTxt1KeyTyped

    private void ageJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ageJTxt1KeyTyped

    private void sumbitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitJBtnActionPerformed
        // TODO add your handling code here:

        try {
            String firstName = firstNameJTxt1.getText();
            String lastName = lastNameJTxt1.getText();
            int age = Integer.parseInt(ageJTxt1.getText());
            String userName = userNameJTxt.getText();
            String password = passwordJTxt.getText();
            String addressLine1 = addtxt1.getText();
            String addressLine2 = addTxt2.getText();
            int aptNumber=Integer.parseInt(aptNumberTxt.getText());
            int pincode = Integer.parseInt(pincodeJTxt.getText());
            String phoneNo=phoneNoJTxt2.getText();
            String email = emailIdJTxt1.getText();

            String gender;

            if (maleJRadiobtn.isSelected()) {
                gender = "Male";
            } else {
                gender = "Female";
            }

            if (firstName.length() == 0 | firstName == null | email.length() == 0
                | email == null | lastName.length() == 0 | lastName == null
                | gender.length() == 0 | addressLine1 == null | addressLine1.length() == 0
                | userName.length() == 0 | userName == null | password.length() == 0
                | password == null ) {
                JOptionPane.showMessageDialog(null, "Please Complete all required fields");
            }
            else if(!Validation.validateTextFieldsForInteger(ageJTxt1)){
                JOptionPane.showMessageDialog(null,"Please enter Valid Age");
            }
            else if(pincodeJTxt.getText().length() != 5){
                JOptionPane.showMessageDialog(null,"Please enter valid Pin Code");
            }
            else  if(!Validation.validateTextFieldsForEmailId(emailIdJTxt1))
            {
                JOptionPane.showMessageDialog(null,"Please enter valid email id");
            }
            else if(!Validation.validateTextFieldsForPhoneNumber(phoneNoJTxt2))
            {
                JOptionPane.showMessageDialog(null,"Please enter valid Primary Phone Number");

            }
           

            else {
                boolean isContain = Validation.checkUniquenessOfUserName(userName, system);
                boolean isPhone= Validation.checkUniquenessOfPhoneNumber(phoneNo, system);
                if (isContain) {
                    JOptionPane.showMessageDialog(null, "UserAccount Already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(isPhone){
                    JOptionPane.showMessageDialog(null, "Phone Number Already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                //                else if(!otp_txt.equals(OTP_GEN)) {
                    //
                    //                        JOptionPane.showMessageDialog(null, "Incorrect OTP Please Enter again and Click on Submit", "Warning", JOptionPane.WARNING_MESSAGE);
                    //                }
                else {
                    Address address=new Address();
                    address.setAddressLine1(addressLine1);
                    address.setAddressLine2(addressLine2);
                    address.setApartmentNo(aptNumber);
                    address.setZipCode(pincode);
                    address.setCity(networkJComboBox.getSelectedItem().toString());
                    Network network=(Network) networkJComboBox.getSelectedItem();
                    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                        if(enterprise instanceof CitizenEnterprise){
                            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                                if(organization instanceof CitizenOrganization){
                                    CitizenOrganizationEmployee coe = (CitizenOrganizationEmployee) organization.getPersonDirectory().createEmployee(firstName, lastName, email, gender, age, address, phoneNo, pincode, org);
                                        organization.getUserAccountDirectory().createUserAccount(userName, password,coe, new CitizenRole());
                                }
                            }
                        }
                    }

                    userProcessContainer.removeAll();
                    JOptionPane.showMessageDialog(null, "Successfully registered");
                    firstNameJTxt1.setText("");
                    lastNameJTxt1.setText("");
                    ageJTxt1.setText("");
                    userNameJTxt.setText("");
                    passwordJTxt.setText("");
                    addtxt1.setText("");
                    addTxt2.setText("");
                    aptNumberTxt.setText("");
                    pincodeJTxt.setText("");
                    phoneNoJTxt2.setText("");
                    emailIdJTxt1.setText("");
                }

            }
        } catch (NumberFormatException num) {
            JOptionPane.showMessageDialog(null, "Please provide All Details", "Incorrect Input", JOptionPane.WARNING_MESSAGE);
        } catch (NullPointerException nul) {
            JOptionPane.showMessageDialog(null, "Please Select Gender", "Incomplete Input", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_sumbitJBtnActionPerformed

    private void phoneNoJTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoJTxt2KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_phoneNoJTxt2KeyTyped

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void aptNumberTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aptNumberTxtKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_aptNumberTxtKeyTyped

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

    }//GEN-LAST:event_networkJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addTxt2;
    private javax.swing.JTextField addtxt1;
    private javax.swing.JTextField ageJTxt1;
    private javax.swing.JTextField aptNumberTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField emailIdJTxt1;
    private javax.swing.JTextField firstNameJTxt1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField lastNameJTxt1;
    private javax.swing.JRadioButton maleJRadiobtn;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField passwordJTxt;
    private javax.swing.JTextField phoneNoJTxt2;
    private javax.swing.JTextField pincodeJTxt;
    private javax.swing.JButton sumbitJBtn;
    private javax.swing.JTextField userNameJTxt;
    // End of variables declaration//GEN-END:variables
}
