

package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.CitizenEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MonitoringEnterprise;
import Business.Network.Network;
import Business.Organization.City.CitizenOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ElectricityWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    EcoSystem system;
    int penidingStatusCount;
    int completedStatusCount;
    int othersCount;
    int sentCount;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,Organization organization,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization =  organization;
        this.system=system;
        valueLabel.setText(enterprise.getName());
        if(enterprise instanceof MonitoringEnterprise || enterprise instanceof CitizenEnterprise){
            requestSummaryBtn.setEnabled(false);
            escalatedRequestsBtn1.setEnabled(false);
        }
        
    }
  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        updateUserJButton = new javax.swing.JButton();
        escalatedRequestsBtn1 = new javax.swing.JButton();
        requestSummaryBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(110, 89, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrative Role Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        userJButton.setBackground(new java.awt.Color(54, 33, 89));
        userJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userJButton.setForeground(new java.awt.Color(255, 255, 255));
        userJButton.setText("Manage User");
        userJButton.setBorder(new javax.swing.border.MatteBorder(null));
        userJButton.setContentAreaFilled(false);
        userJButton.setMaximumSize(new java.awt.Dimension(6, 28));
        userJButton.setMinimumSize(new java.awt.Dimension(6, 28));
        userJButton.setPreferredSize(new java.awt.Dimension(6, 28));
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 310, 40));

        manageEmployeeJButton.setBackground(new java.awt.Color(54, 33, 89));
        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.setBorder(new javax.swing.border.MatteBorder(null));
        manageEmployeeJButton.setContentAreaFilled(false);
        manageEmployeeJButton.setMaximumSize(new java.awt.Dimension(6, 28));
        manageEmployeeJButton.setMinimumSize(new java.awt.Dimension(6, 28));
        manageEmployeeJButton.setPreferredSize(new java.awt.Dimension(6, 28));
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 310, 40));

        manageOrganizationJButton.setBackground(new java.awt.Color(54, 33, 89));
        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrganizationJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.setBorder(new javax.swing.border.MatteBorder(null));
        manageOrganizationJButton.setContentAreaFilled(false);
        manageOrganizationJButton.setMaximumSize(new java.awt.Dimension(6, 28));
        manageOrganizationJButton.setMinimumSize(new java.awt.Dimension(6, 28));
        manageOrganizationJButton.setPreferredSize(new java.awt.Dimension(6, 28));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 310, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, 30));

        updateUserJButton.setBackground(new java.awt.Color(54, 33, 89));
        updateUserJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateUserJButton.setForeground(new java.awt.Color(255, 255, 255));
        updateUserJButton.setText("Update Employee");
        updateUserJButton.setBorder(new javax.swing.border.MatteBorder(null));
        updateUserJButton.setContentAreaFilled(false);
        updateUserJButton.setMaximumSize(new java.awt.Dimension(6, 28));
        updateUserJButton.setMinimumSize(new java.awt.Dimension(6, 28));
        updateUserJButton.setPreferredSize(new java.awt.Dimension(6, 28));
        updateUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserJButtonActionPerformed(evt);
            }
        });
        add(updateUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 310, 40));

        escalatedRequestsBtn1.setBackground(new java.awt.Color(54, 33, 89));
        escalatedRequestsBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        escalatedRequestsBtn1.setForeground(new java.awt.Color(255, 255, 255));
        escalatedRequestsBtn1.setText("View Escalated Requests");
        escalatedRequestsBtn1.setBorder(new javax.swing.border.MatteBorder(null));
        escalatedRequestsBtn1.setContentAreaFilled(false);
        escalatedRequestsBtn1.setMaximumSize(new java.awt.Dimension(6, 28));
        escalatedRequestsBtn1.setMinimumSize(new java.awt.Dimension(6, 28));
        escalatedRequestsBtn1.setPreferredSize(new java.awt.Dimension(6, 28));
        escalatedRequestsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalatedRequestsBtn1ActionPerformed(evt);
            }
        });
        add(escalatedRequestsBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 310, 40));

        requestSummaryBtn.setBackground(new java.awt.Color(54, 33, 89));
        requestSummaryBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestSummaryBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestSummaryBtn.setText("Request By Status");
        requestSummaryBtn.setBorder(new javax.swing.border.MatteBorder(null));
        requestSummaryBtn.setContentAreaFilled(false);
        requestSummaryBtn.setMaximumSize(new java.awt.Dimension(6, 28));
        requestSummaryBtn.setMinimumSize(new java.awt.Dimension(6, 28));
        requestSummaryBtn.setPreferredSize(new java.awt.Dimension(6, 28));
        requestSummaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSummaryBtnActionPerformed(evt);
            }
        });
        add(requestSummaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 310, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        Network networkEmp =  null;
        for(Network network : system.getNetworkList()){
            for(Enterprise enterpriseCheck : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterpriseCheck == enterprise){
                    networkEmp = network;
                }
            }
        }
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),networkEmp);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

     public void populateTable(JPanel dataJPanel) {
       for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise instanceof CitizenEnterprise){
        for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof CitizenOrganization){
            for(UserAccount account:o.getUserAccountDirectory().getUserAccountList()) {
            for(WorkRequest request:account.getWorkQueue().getWorkRequestList()){
                if(request.getRequestType().equalsIgnoreCase(ElectricityWorkRequest.WorkRequestType.ElectricityWorkRequest.getValue()))
                if(request.getStatus().equalsIgnoreCase("Pending")){
                    penidingStatusCount++;
                } else if(request.getStatus().equalsIgnoreCase("Completed")){
                    completedStatusCount++;
                } else if(request.getStatus().equalsIgnoreCase("Processing")){
                    othersCount++;
                } else if(request.getStatus().equalsIgnoreCase("Sent")){
                    sentCount++;
                }
            }
            } 
        }
        }
                }
            }}
       }
       
    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void updateUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserJButtonActionPerformed
        UpdateEmployeeJPanel updateUserAccountJPanel = new UpdateEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise);
        userProcessContainer.add("UpdateUserAccountJPanel", updateUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateUserJButtonActionPerformed

    private void escalatedRequestsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalatedRequestsBtn1ActionPerformed
        // TODO add your handling code here:
        ViewEscalatedRequestsJPanel viewEscalatedRequestsJPanel = new ViewEscalatedRequestsJPanel(userProcessContainer, enterprise.getOrganizationDirectory() ,enterprise);
        userProcessContainer.add("ViewEscalatedRequestsJPanel", viewEscalatedRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_escalatedRequestsBtn1ActionPerformed

    private void requestSummaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSummaryBtnActionPerformed
        ViewRequestsByStatusJPanel requestsByStatusJPanel = new ViewRequestsByStatusJPanel();
        populateTable(requestsByStatusJPanel);
    }//GEN-LAST:event_requestSummaryBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton escalatedRequestsBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton requestSummaryBtn;
    private javax.swing.JButton updateUserJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
